disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ben Cole"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Microsoft Endpoint Management"

  [params.author]
  name = "Ben Cole"

    [[params.author.links]]
    linkedin = "https://www.linkedin.com/in/bencole1996/"

["params.author"]
headline = "Windows Endpoint Management with ConfigMgr, Intune, Powershell and More"
